name: 'Hello world'
description: 'Simple task for Hello World'
inputs:
  who-to-greet:
    description: 'Who to great'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time when we greated you'
runs:
  using: 'docker'
  image: 'Dockerfile.github'
  args:
    - ${{ inputs.who-to-greet }}